### ISSUE TITLE
User and Group structs Encapsulating Write as well as Read

### ISSUE THREAD

**Issue by MggMuggins** [redox-os/users#6]
Currently the `User` and `Group` structs only provide API's for getting things like all the groups/users on the system and getting access to that info, as well as checking password in `User`'s case.

What if a Group struct could also write to the group file, something like this:
```Rust
let mut group = get_group_by_name("sudo");
group.users.push("my-user".to_string());
group.write();
```

The trouble is that I'm not sure how one would make sure to get writes correct, although this seems fairly necessary as this is a system API that should be used an awful lot, and should be fairly easy and intuitive to use, and difficult to break.

**Comment by jackpot51** [comment]
I would prefer to have a Groups and Users struct upon which the get_by_name and write function can be called. These structs would be borrowed when you do get_by_name

**Comment by MggMuggins** [comment]
So expand the roles of `AllUsers` and `AllGroups` to encapsulate the whole set of groups and users on the system? So for example, these methods:
```Rust
impl AllUsers {

fn new() -> AllUsers {}
fn get_by_name<T: AsRef<str>>(name: T) -> Option<&User> {}
fn get_by_id(gid: usize) -> Option<&User> {}
fn add(User) -> Result<(), io::Error> {}
fn add(user: &str, uid: u32, gid: u32, name: &str, home: &str, shell: &str) -> Result<(), io::Error> {}

}
```
I would almost recommend continuously synchronized state with `/etc/passwd`, if it could be implemented in such a way that we don't even have an unstable passwd file.

**Comment by goyox86** [comment]
Yeah that looks cool @MggMuggins.

**Comment by MggMuggins** [comment]
For the API, I would say we need to ask ourselves what is necessary functionality for the library, and make sure that we have that functionality and no more. Keep the vision narrow. Here's the operations so far that I've heard of or thought up.

For a specific Group Struct:
 * Determine if a user is part of this group (performance sensitive)
 * Add a user to this group
 * Remove a user from this group
 * Provide an Iterator over all the users in the group?

For a specific User struct:
 * Assert that a given password matches the stored hash
 * Get all the information associated with this user (shell, home, etc.)

For AllGroups:
 * Provide an iterator
 * Add (take both `Group` and the required info?)
 * Remove (by both name and gid)

More coming soon...

**Comment by jackpot51** [comment]
We will need to be able to change a user's password, for example.

**Comment by MggMuggins** [comment]
Yes. I'm wondering if a less OOP approach to this problem would be a good thing. Not sure what that would look like. I'll find a whiteboard and do some brainstorming tomorrow, see what I come up with.

**Comment by jackpot51** [comment]
That's good @MggMuggins

**Comment by MggMuggins** [comment]
As of https://github.com/redox-os/users/pull/8
